services:

  web:

    image: krasko84/bgapp-web1
    
    deploy:
        replicas: 3

    ports:

      - 8080:80

    volumes:

      - "/home/vagrant/bgapp/web:/var/www/html:ro"

    networks:

      - app-network

  db:

    image: krasko84/bgapp-db

    networks:

      - app-network

    environment:

      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password

    secrets: 
        - db_root_password

secrets:
    db_root_password:
      external: true

networks:

    app-network:
